CREATE DATABASE IF NOT EXISTS stocks DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS StockInfo(sid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(10) NOT NULL UNIQUE KEY, name VARCHAR(10) NOT NULL, market VARCHAR(5) NOT NULL, symbol VARCHAR(10) NOT NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS StockQuotes(sid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(10) NOT NULL UNIQUE KEY, trade_date DATE NOT NULL, time TIME NOT NULL, open FLOAT, high FLOAT, low FLOAT, last FLOAT NOT NULL, close FLOAT, volume FLOAT NOT NULL, turnover FLOAT NOT NULL, turnover_rate FLOAT NOT NULL, volume_ratio FLOAT NOT NULL, limit_up FLOAT NOT NULL, limit_down FLOAT NOT NULL, preclose FLOAT NOT NULL, flow_equity FLOAT NOT NULL, total_equity FLOAT NOT NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS StockDailys(sid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(10) NOT NULL, open FLOAT, high FLOAT, low FLOAT, close FLOAT, volume FLOAT NOT NULL, turnover FLOAT NOT NULL, trade_date DATE NOT NULL, UNIQUE KEY code(code, trade_date))ENGINE=InnoDB DEFAULT CHARSET=utf8;
